import type { ProjectSummary } from './strapi';

const img = (seed: string, w = 900, h = 1200) => ({
    url: `https://picsum.photos/seed/${seed}/picsum/${w}/${h}`,
    width: w,
    height: h,
});

const base = { category: null, featured: null };

export const MOCK_PROJECTS: ProjectSummary[] = [
    {
        ...base,
        id: 'm1',
        order: 1,
        year: 2025,
        title: "Changement d'état",
        slug: 'changement-detat',
        subtitle: 'Performance textile · Paris 2025',
        shortDescription: 'A performance in which the body becomes thread, unraveling through embroidered gestures.',
        featuredImage: img('changement', 900, 1200),
    },
    {
        ...base,
        id: 'm2',
        order: 2,
        year: 2025,
        title: 'La Tisseuse',
        slug: 'la-tisseuse',
        subtitle: 'Installation textile · Paris 2025',
        shortDescription: 'A large-format textile installation exploring the figure of the weaver as resistance.',
        featuredImage: img('tisseuse', 900, 1200),
    },
    {
        ...base,
        id: 'm3',
        order: 3,
        year: 2025,
        title: 'Résidence NY20+',
        slug: 'residence-ny20',
        subtitle: 'Résidence artistique · New York 2025',
        shortDescription: 'A multi-year research residency on migration, language, and the body in transit.',
        featuredImage: img('ny20', 900, 1200),
    },
    {
        ...base,
        id: 'm4',
        order: 4,
        year: 2024,
        title: 'Au Milieu de Murs Fragiles',
        slug: 'au-milieu-de-murs-fragiles',
        subtitle: 'Installation in situ · 2021–2025',
        shortDescription: 'Walls built from embroidered gauze — a meditation on borders between bodies and spaces.',
        featuredImage: img('murs', 900, 1200),
    },
    {
        ...base,
        id: 'm5',
        order: 5,
        year: 2022,
        title: 'Volver al Gesto',
        slug: 'volver-al-gesto',
        subtitle: 'Performance · Buenos Aires 2022',
        shortDescription: 'A return to the ancestral gesture: the body remembers what language has forgotten.',
        featuredImage: img('gesto', 900, 1200),
    },
    {
        ...base,
        id: 'm6',
        order: 6,
        year: 2022,
        title: 'Híbrido',
        slug: 'hibrido',
        subtitle: 'Fotografía híbrida · 2022',
        shortDescription: 'Wet-plate and silver gelatin processes collide with contemporary portraiture.',
        featuredImage: img('hibrido', 900, 1200),
    },
    {
        ...base,
        id: 'm7',
        order: 7,
        year: 2023,
        title: 'Diez Rollos 35mm',
        slug: 'diez-rollos-35mm',
        subtitle: 'Fotografía · 2023',
        shortDescription: 'Ten rolls of film shot in the margins of Buenos Aires — a city seen sideways.',
        featuredImage: img('rollos', 900, 1200),
    },
    {
        ...base,
        id: 'm8',
        order: 8,
        year: 2018,
        title: 'Habitar los espacios',
        slug: 'habitar-los-espacios',
        subtitle: 'Instalación · 2018',
        shortDescription: "Site-specific installation questioning what it means to occupy a place with one's own body.",
        featuredImage: img('habitar', 900, 1200),
    },
    {
        ...base,
        id: 'm9',
        order: 9,
        year: 2017,
        title: 'El torso no miente',
        slug: 'el-torso-no-miente',
        subtitle: 'Performance · 2017',
        shortDescription: 'The torso as archive: scar tissue, posture, and the politics of the upright body.',
        featuredImage: img('torso', 900, 1200),
    },
    {
        ...base,
        id: 'm10',
        order: 10,
        year: 2016,
        title: 'Dilucidar',
        slug: 'dilucidar',
        subtitle: 'Fotografía alternativa · 2016',
        shortDescription: 'Alternative photography processes — cyanotype and gum bichromate — on found fabric.',
        featuredImage: img('dilucidar', 900, 1200),
    },
    {
        ...base,
        id: 'm11',
        order: 11,
        year: 2015,
        title: 'Certificado de ausencia',
        slug: 'certificado-de-ausencia',
        subtitle: 'Instalación · 2015',
        shortDescription: 'A bureaucratic archive of erasure — official documents stamped with the names of the disappeared.',
        featuredImage: img('certificado', 900, 1200),
    },
];
